### ISSUE TITLE
Installing xterm in my atom IDE fails again and again.

### ISSUE THREAD

**Issue by amanarora9848** [dwb/atom-xterm#12]
The detailed report as received from the ide is:
Installing “xterm@1.2.1” failed.
> keyboard-layout@2.0.13 install /tmp/apm-install-dir-118120-12168-9a0la6.70h1uivn29/node_modules/xterm/node_modules/keyboard-layout
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-118120-12168-9a0la6.70h1uivn29/node_modules/xterm/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o
keyboard-layout-manager.target.mk:96: recipe for target 'Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o' failed
make: Leaving directory '/tmp/apm-install-dir-118120-12168-9a0la6.70h1uivn29/node_modules/xterm/node_modules/keyboard-layout/build'
/tmp/apm-install-dir-118120-12168-9a0la6.70h1uivn29
`-- (empty)

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
In file included from ../src/keyboard-layout-manager-linux.cc:1:0:
../src/keyboard-layout-manager.h:7:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-53-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118120-12168-9a0la6.70h1uivn29/node_modules/xterm/node_modules/keyboard-layout
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118120-12168-9a0la6.70h1uivn29/package.json'
npm WARN apm-install-dir-118120-12168-9a0la6.70h1uivn29 No description
npm WARN apm-install-dir-118120-12168-9a0la6.70h1uivn29 No repository field.
npm WARN apm-install-dir-118120-12168-9a0la6.70h1uivn29 No README data
npm WARN apm-install-dir-118120-12168-9a0la6.70h1uivn29 No license field.
npm ERR! Linux 4.8.0-53-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/aman/.atom/.apm/.apmrc" "--userconfig" "/home/aman/.atom/.apmrc" "install" "/tmp/d-118120-12168-xsbxvy.dinxrsh5mi/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! keyboard-layout@2.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keyboard-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118120-12168-9a0la6.70h1uivn29/npm-debug.log
npm ERR! code 1

**Comment by josineto** [comment]
This also happens with me. Below the APM log:
[2019-07-29T04_48_43_671Z-debug.log](https://github.com/dwb/atom-xterm/files/3440306/2019-07-29T04_48_43_671Z-debug.log)

My system:
Manjaro Linux 64bit
Atom 1.38.2 x64
