### ISSUE TITLE
Can not update to 1.1.0

### ISSUE THREAD

**Issue by bbuhler** [dwb/atom-xterm#4]
After failing to update to xterm 1.1.0, Atom show following output:
```
> keyboard-layout@2.0.13 install /tmp/apm-install-dir-11784-16724-1xjnwef.egcf03sor/node_modules/xterm/node_modules/keyboard-layout
> node-gyp rebuild

make: Verzeichnis „/tmp/apm-install-dir-11784-16724-1xjnwef.egcf03sor/node_modules/xterm/node_modules/keyboard-layout/build“ wird betreten
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o
keyboard-layout-manager.target.mk:96: die Regel für Ziel „Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o“ scheiterte
make: Verzeichnis „/tmp/apm-install-dir-11784-16724-1xjnwef.egcf03sor/node_modules/xterm/node_modules/keyboard-layout/build“ wird verlassen
/tmp/apm-install-dir-11784-16724-1xjnwef.egcf03sor
└── (empty)


../src/keyboard-layout-manager-linux.cc:5:37: fatal error: X11/extensions/XKBrules.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o] Fehler 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.0-26-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11784-16724-1xjnwef.egcf03sor/node_modules/xterm/node_modules/keyboard-layout
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11784-16724-1xjnwef.egcf03sor/package.json'
npm WARN apm-install-dir-11784-16724-1xjnwef.egcf03sor No description
npm WARN apm-install-dir-11784-16724-1xjnwef.egcf03sor No repository field.
npm WARN apm-install-dir-11784-16724-1xjnwef.egcf03sor No README data
npm WARN apm-install-dir-11784-16724-1xjnwef.egcf03sor No license field.
npm ERR! Linux 4.10.0-26-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/bbuhler/.atom/.apm/.apmrc" "--userconfig" "/home/bbuhler/.atom/.apmrc" "install" "/tmp/d-11784-16724-pupeon.jqe8060f6r/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! keyboard-layout@2.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keyboard-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11784-16724-1xjnwef.egcf03sor/npm-debug.log
npm ERR! code 1
```
I am on Linux with:
```
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by dwb** [comment]
Hi, really sorry for getting back so late, I didn't see the email for this one 😕

Make sure you have the macOS-default `python` in scope – for example, I'm using pyenv, and I had to do
```
$ (pyenv shell system && apm install xterm)
```

**Comment by bbuhler** [comment]
What is the macOS-default python? I am on Linux.

**Comment by codyopel** [comment]
@bbuhler 
The error is that you are missing libxkbfile.  You need the following to rebuild keyboard-layout-manager (and possibly other X.Org libraries).
- libx11
- libxkbfile
- kbproto
- xproto

If you have any libraries installed in non-standard prefixes you can set the CPATH & LIBRARY_PATH environment variables.

**Comment by dwb** [comment]
@codyopel thanks for that :)
@bbuhler sorry for my assumption! A very similar error is the result of me (regularly) forgetting to use the right `python`.
